# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [ ]:
s.split()

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
'The diameter of {0} is {1} kilometer'.format(planet,diameter)

'The diameter of Earth is 12742 kilometer'

## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
print(d["k1"][3]["tricky"][3]["target"][3])

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
arr1=np.zeros(10)
print(arr1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
arr2=np.ones(10)*5
print(arr2)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [ ]:
arr3=np.arange(20,36,2)
print(arr3)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a,b),axis=None)

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [ ]:
A = np.random.randint(10, size=(3,2))
df = pd.DataFrame(A,columns=['Coloumn A', 'Coloumn B'])
df

Coloumn A  Coloumn B
0          1          8
1          8          0
2          2          5

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
dict_a = {
   'coloumn_a':[1,2,3], 
   'coloumn_b': [2,5,6], 
}
df = pd.DataFrame(dict_a)
df

coloumn_a  coloumn_b
0          1          2
1          2          5
2          3          6

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
list_a = [['John', 23], ['Jane', 25], ['Mary', 21]]
df = pd.DataFrame(list_a,columns=['Name', 'Age'])
df

Name  Age
0  John   23
1  Jane   25
2  Mary   21